title: Hardik Jaiswal
description: Building things in bits and bytes ☘️
logo: /assets/img/head-icon.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
# Rebuilding site